config/routes.rb
AnabtaTecM::Application.routes.draw do
  resources :posts
resources :home

    match 'gallery/' => 'home#gallery'
      match 'about/' => 'home#about'
      match 'posts/' => 'posts#index'
match "contact", to: "contact#index", as: "contact"
  match "send_email", to: "contact#send_email",
  as: "send_email", method: :post

  root :to => 'home#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :fullname, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	
  def contact
  end

  def dispatch_email
    user_info = params[:user_info]
    if ContactMailer.send_email(user_info).deliver
      flash[:notice] = "Sent!"
    else
      flash[:notice] = "Could't send you message."
    end
    redirect_to contact_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contact/index.html.erb
<section id="content">

<div class="zerogrid block">	

<div class="row block04">

<div class="col16">

<section>

<p>Home >> Get in Touch!</p>

</section>

</div>

</div>

<div class="row block05">

<div id="main-content" class="col-2-3">

<div class="comment">

Your email address will not be published. Required fields are marked *
<p>Riyad Faek Anabtawi .- CEO, will be in touch shortly.</p>

<form>

<%= form_tag dispatch_email_path, method: :post do %>
 <p> <%= label_tag "user_info[name]", "Name" %></p>
  <p><%= text_field_tag "user_info[name]" %></p>
  <p><%= label_tag "user_info[email]", "Email" %></p>
  <p><%= text_field_tag "user_info[email]" %></p>
  <p><%= label_tag "user_info[message]", "Message" %></p>
 <p> <%= text_area_tag "user_info[message]", "" %></p>

 <p> <%= submit_tag "Send" %></p>
<% end %>

</div>

</div>

<div id="sidebar" class="col-1-3">
        <section>
          <div class="heading"><h2>About us</h2></div>
          <div class="content">
            <img src="/assets/thumb2.jpg" />
            <p align="justify">AnabtaTec is an Brazilian-Argentinian based outsourcing and software firm offering extended IT solutions and helping our clients reduce Time To Market (TTM) and enhance Return On Investment (ROI). Spezialazing in Ruby on Rails, iOS, Android, PHP, HTML5 and CSS3 Development.</p>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Services</h2></div>
          <div class="content">
            <ul>
              <li><a href="#">PHP</a></li>
              <li><a href="#">Ruby on Rails</a></li>
              <li><a href="#">iOS</a></li>
                 <li><a href="#">Android</a></li>
                    <li><a href="#">Networking</a></li>
                       <li><a href="#">Advanced IT Linux Infra-Structure</a></li>
                          <li><a href="#">HTML5</a></li>
                             <li><a href="#">CSS3</a></li>
                                <li><a href="#">Jquery Mobile</a></li>
            </ul>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Latest Tweets</h2></div>
          <div class="content">
            <a class="twitter-timeline"  href="https://twitter.com/AnabtaTec"  data-widget-id="245951997168197632">Tweets by @AnabtaTec</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

          </div>
        </section>
      </div>

</div>

</div>

</section>

app/views/contact/send_email.html.erb
<h1>MyApp's contact form</h1>

<p>Name: <%= @user_info["name"] %></p>
<p>Email: <%= @user_info["email"] %></p>
<p>Message: <%= @user_info["message"] %></p>

app/views/home/about.html.erb
<body>


<section class="featured">


      <li><img src="/assets/earth.png"/></li>
 
 
</section>
      
<section id="content">
  <div class="zerogrid block">  
    <div class="row block04">
      <div class="col16">
        <section>
          <p>Home >> About</p>
        </section>
      </div>
    </div>
    
    <div class="row block05">
      <div id="main-content" class="col-2-3">
        <article>
         
          <div class="content">
            <img src="/assets/slide1.jpg" />
            <p>AnabtaTec is an Brazilian-Argentinian based outsourcing and software firm offering extended IT solutions and helping our clients reduce Time To Market (TTM) and enhance Return On Investment (ROI). Spezialazing in Ruby on Rails, iOS, Android, PHP, HTML5 and CSS3 Development.</p>
            <p>Since 2009, we have been servicing startups, SMEs, web design/development and IT consulting firms across the globe. Today, we are a 150+ people company.</p>

            <p>Trust, pride in what we do and teamwork form the tenets of our culture. Having worked with clients across different geographies and industry verticals has enabled us to perfect our delivery model to offer world class quality.</p>

            <p>For our clients, it is not about finding a software outsourcing vendor, but about having a trusted development partner who can deliver and help them succeed. Our processes are client driven and we assimilate our clients delivery, quality and measurement processes into our own.</p>

             <p>We constantly improvise on our processes to enhance our service standards to exceed customer expectations, always.</p>

   

              <p> Contact us today to learn more about how we can help your business grow.</p>

          </div>
        </article>
       
      </div>
      <div id="sidebar" class="col-1-3">
        <section>
          <div class="heading"><h2>Other Services</h2></div>
          <div class="content">
            <img src="/assets/services.png" />
            <p align="justify"><li>Advanced IT Linux Infrastructure</li>
              <li>CISCO Networking</li>
              <li>Network Administration</li>
              <li>Linux Servers</li>

            </p>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Services</h2></div>
          <div class="content">
            <ul>
              <li><a href="#">PHP</a></li>
              <li><a href="#">Ruby on Rails</a></li>
              <li><a href="#">iOS</a></li>
                 <li><a href="#">Android</a></li>
                    <li><a href="#">Networking</a></li>
                       <li><a href="#">Advanced IT Linux Infra-Structure</a></li>
                          <li><a href="#">HTML5</a></li>
                             <li><a href="#">CSS3</a></li>
                                <li><a href="#">Jquery Mobile</a></li>
            </ul>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Latest Tweets</h2></div>
          <div class="content">
            <a class="twitter-timeline"  href="https://twitter.com/AnabtaTec"  data-widget-id="245951997168197632">Tweets by @AnabtaTec</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

          </div>
        </section>
      </div>
    </div>
  </div>
</section>



</body>

app/views/home/gallery.html.erb
<section id="content">
  <div class="zerogrid block">  
    <div class="row block04">
      <div class="col16">
        <section>
          <p>Home >> Portfolio</p>
        </section>
      </div>
    </div>
    
    <div class="row block05">
      <div id="main-content" class="col-2-3">
     <ul class="polaroids">

  <li><a href="http://anabtatec.com" class="pic-1"><img src="http://anabtatec.com/images/port1.png" alt="HTML5, CSS3" title="HTML5, CSS3"/></li>

  <li><a href="http://anabtatec.com" class="pic-2"><img src="http://anabtatec.com/images/port2.png" alt="css3" title="css3"/></li>

  <li><a href="http://anabtatec.com" class="pic-3"><img src="http://anabtatec.com/images/port3.png" alt="php, cakephp" title="php, cakephp"/></li>

  <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/port5.png" alt="html5, css3" title="html5, css3"/></li>

 <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/m.ranabtawi.com.png" alt="iOS, jquery mobile" title="iOS, jquery mobile"/></li>

 <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/inside.png" alt="php development" title="php development"/></li>

 <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/rest.png" alt="html5, css3"title="html5, css3" /></li>

 <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/ecur.png" alt="html5, css3" title="html5, css3"/></li>

  <li><a href="http://anabtatec.com" class="pic-6"><img src="http://anabtatec.com/images/sedeva.png" alt="HTML5, css3" title="HTML5, css3"/></li>

   <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/proagile.png" alt="PHP Development" title="PHP Development"/></li>

    <li><a href="http://anabtatec.com" class="pic-4"><img src="http://anabtatec.com/images/proagile-mobile.png" alt="iOS Development, jquery mobile" title="iOS Development, jquery mobile"/></li>

</ul>
       <!-- <div id="container2">
       

</div> -->
      </div>
      <div id="sidebar" class="col-1-3">
        <section>
          <div class="heading"><h2>About us</h2></div>
          <div class="content">
            <img src="/assets/thumb2.jpg" />
            <p align="justify">AnabtaTec is an Brazilian-Argentinian based outsourcing and software firm offering extended IT solutions and helping our clients reduce Time To Market (TTM) and enhance Return On Investment (ROI). Spezialazing in Ruby on Rails, iOS, Android, PHP, HTML5 and CSS3 Development.</p>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Services</h2></div>
          <div class="content">
            <ul>
              <li><a href="#">PHP</a></li>
              <li><a href="#">Ruby on Rails</a></li>
              <li><a href="#">iOS</a></li>
                 <li><a href="#">Android</a></li>
                    <li><a href="#">Networking</a></li>
                       <li><a href="#">Advanced IT Linux Infra-Structure</a></li>
                          <li><a href="#">HTML5</a></li>
                             <li><a href="#">CSS3</a></li>
                                <li><a href="#">Jquery Mobile</a></li>
            </ul>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Latest Tweets</h2></div>
          <div class="content">
            <a class="twitter-timeline"  href="https://twitter.com/AnabtaTec"  data-widget-id="245951997168197632">Tweets by @AnabtaTec</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

          </div>
        </section>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<body>


<section class="featured">
  <div class="rslides_container">
    <ul class="rslides" id="slider">
      <li><img src="/assets/php.jpg"/></li>
      <li><img src="/assets/jquery.jpg"/></li>
      <li><img src="/assets/ror.jpg"/></li>
       <li><img src="/assets/ios.jpg"/></li>
       <li><img src="/assets/apps.jpg"/></li>

    </ul>
  </div>
</section>
      

<section id="content">
  <div class="zerogrid block">    
    <div class="row block01">
      <div class="col04">
        <section>
          <div class="heading">
            <img src="/assets/laptop.png"/>
            <h2>Planning</h2>
          </div>
          <div class="content">
            <p align="justify">Planning The Mobile App, is the first step to create an organized blueprint of your Poroject. Picking up your business requirements and needs, as well as expectations to create you Dream Mobile Application.</p>
            <br><br>
            <p align="justify" class="more"><a class="button" href="single.html">Read more</a></p>
          </div>
        </section>
      </div>
      <div class="col04">
        <section>
          <div class="heading">
            <img src="/assets/chart.png"/>
            <h2>Developing</h2>
          </div>
          <div class="content">
            <p align="justify">Developing The Mobile App, is the second step. Here comes coding. AnabtaTec offers iOS Developing (gaming and dinamic mobile applications for any kind of system requirements), Android Developping, Jquery Mobile Development, PHP, HTML5 and CSS3.</p>
            <p align="justify" class="more"><a class="button" href="single.html">Read more</a></p>
          </div>
        </section>
      </div>
      <div class="col04">
        <section>
          <div class="heading">
            <img src="/assets/history.png"/>
            <h2>Designing</h2>
          </div>
          <div class="content">
            <p align="justify">The Design is very important, we can use HTML5 and CSS 3 to make your main WebSite responsive to many different screens and browsers. On the other hand Designing just for specified devices is also an option.- iOS - Android- HTML5 - CSS3 - JqueryMobile</p>
            <p align="justify" class="more"><a class="button" href="single.html">Read more</a></p>
          </div>
        </section>
      </div>
      <div class="col04">
        <section>
          <div class="heading">
            <img src="/assets/web.png"/>
            <h2>Features</h2>
          </div>
          <div class="content">
            <p align="justify">Build relationships - Reinforce your brand - Increase your visibility - Increase your accessibility - Increase sell-through - Increase exposure across mobile devices - Connect you with on-the-go consumers - Generate repeat business - Enhance your social networking strategies </p>
            <p align="justify" class="more"><a class="button" href="single.html">Read more</a></p>
          </div>
        </section>
      </div>
    </div>
    
    <div class="row block02">
      <div class="col16">
        <section>
          <p align="justify">Perfection (in design) is achieved not when there is nothing more to add, but rather when there is nothing more to take away .- Antoine de Saint-Exupery</p>
        </section>
      </div>
    </div>
    
    <div class="row block03">
      <div class="col-1-3">
        <section>
          <div class="heading">Ruby on Rails</div>
          <div class="content">
            <img src="/assets/3.png" />
            <p align="justify">Framework implemented by AnabtaTec to provide customers agile, scalable web applications. Some of the largest sites are running with Ruby on Rails include Twitter, Github, Yammer, Scribd, Groupon, Shopify, and Basecamp.</p>
          
          </div>
        </section>
      </div>
      <div class="col-1-3">
        <section>
          <div class="heading">HTML5 and CSS3 Responsive Desing</div>
          <div class="content">
            <img src="/assets/1.png" />
            <p align="justify">HTML5 on its own cannot be used for animation and interactivity — it must be supplemented with CSS3 or JavaScript. Making it better to create responsive web designs and really atractive WebSites and Apps</p>
       
          </div>
        </section>
      </div>
      <div class="col-1-3">
        <section>
          <div class="heading">iOS Mobile Development</div>
          <div class="content">
            <img src="/assets/2.png" />
            <p align="justify"> The most popular iPhone apps are very easy to use and can be quite enjoyable. This would make your company’s app more desirable to use versus the more traditional methods to acquire your products or services. The more enjoyment the customer receives in using your app, the better your relationship which can translate to higher sales. </p>
         
          </div>
        </section>
      </div>
    </div>
  </div>
</section>



</body>

app/views/layouts/_footer.html.erb
<footer>
  <div class="wrapfooter">
  <p>Copyright © 2010 - 2014 <a href="http://mobile.anabtatec.com" target="_blank">Mobile</a>  - <a href="http://mobi.anabtatec.com" target="_blank">Ruby on Rails</a>  - <a href="http://html.anabtatec.com" target="_blank">HTML5</a>  - <a href="http://anabtatec.com" target="_blank">CSS3</a>  - <a href="http://php.anabtatec.com" target="_blank">PHP</a>  - <a href="http://anabtatec.com" target="_blank">iOS</a>  - <a href="http://www.anabtatec.com" target="_blank">JqueryMobile</a>  - <a href="http://android.anabtatec.com" target="_blank">Android</a>  .- <a href="http://www.anabtatec.com" target="_blank">Front &amp; Back End Development </a> <a href="http://www.linkedin.com/profile/view?id=242325376&trk" target="_blank"> by Riyad Faek Anabtawi</a></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header> 
  <div id="logo"><a href="http://anabtatecmobile.com"><img src="/assets/logo.png"/></a></div>
  
  <nav>
    <ul>
       <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Posts', posts_path %></li>
      <li><%= link_to 'Gallery', gallery_path %></li>
     <li><%= link_to 'About', about_path %></li>
 <li><%= link_to 'Contact', contact_path %></li>
    </ul>
  </nav>
</header>

<div class="social">
    <div class="shareicons">
      <ul>
        <li><a href="#"><img src="/assets/Active-RSS-icon.png" title="RSS AnabtaTec"/></a></li>
        <li><a href="http://facebook.com/AnabtaTec"><img src="/assets/Active-Facebook-icon.png" title="Facebook AnabtaTec"/></a></li>
        <li><a href="https://plus.google.com/110599319717131415895"><img src="/assets/Active-Google-plus-icon.png" title="Google+ AnabtaTec"/></a></li>
        <li><a href="http://twitter.com/AnabtaTec"><img src="/assets/Active-Twitter-icon.png" title="Twitter AnabtaTec"/></a></li>
      </ul>
    </div>
    
   <!-- <div id="search">
      <div class="button-search"></div>
      <input type="text" value="Search..." onfocus="if (this.value == &#39;Search...&#39;) {this.value = &#39;&#39;;}" onblur="if (this.value == &#39;&#39;) {this.value = &#39;Search...&#39;;}">
    </div>
-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>AnabtaTec Mobile - Ruby on Rails, HTML5, CSS3, PHP, iOS, JqueryMobile, Android, Advanced IT Infrastructure.- Front &amp; Back End Development </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<meta name="description" content="AnabtaTec Mobile, cakephp, Ruby on Rails, HTML5, CSS3, PHP, iOS, Jquery Mobile, Android, php development, Advanced IT Infrastructure, Front &amp; Back End Development ">
	<meta name="keywords" content="AnabtaTec Mobile, cakephp, Ruby on Rails, HTML5, CSS3, PHP, iOS, Jquery Mobile, Android, php development, Advanced IT Infrastructure, Front &amp; Back End Development ">
	<meta name="author" content="www.anabtatec.com">
	<meta name="google-site-verification" content="0xJbRrQShqQTtO6wT9C_enAKksYzjR2FR2lxRRWRoo8" />
 <meta name="googlebot" content="index, follow"/>
  <meta name="robots" content="index, follow"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
		<script src="/assets/html5.js"></script>
		<script src="/assets/css3-mediaqueries.js"></script>
	<![endif]-->
	<link href='http://anabtatec.com/favicon.ico' rel='icon' type='image/x-icon'/>
	<script>
    $(function () {
      $("#slider").responsiveSlides({
        auto: true,
        pager: false,
        nav: true,
        speed: 500,
        maxwidth: 962,
        namespace: "centered-btns"
      });
    });
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-37907754-2', 'anabtatec.com');
  ga('send', 'pageview');

</script>
</head>
<body>
<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div align="center" id="error_explanation">
      <h2 align="center"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div align="left" style="background:#000; border-radius:10px;">
  <div style="color:#FF4500;" align="center" class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div style="color:#FF4500;" align="center" class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div style="color:#FF4500;"  align="center"class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <br><br>
  <div style="color:#FF4500;" align="center" class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section id="content">
  <div class="zerogrid block">  
    <div class="row block04">
      <div class="col16">
        <section>
          <p>Home >> Posts</p>
        </section>
      </div>
    </div>
    
    <div class="row block05">
      <div id="main-content" class="col-2-3">
        <% @posts.each do |post| %>
        <article>
          <div class="heading">
            <h2><a href=""><%= post.title %></a></h2>
            <div class="info">Posted by <%= post.fullname %>  | <%= link_to 'Show Post', post %> | <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
          </div>
          <div class="content">
            
            <p><%= post.body %></p>
          </div>
        </article>
         <% end %>
        <%= link_to 'Write New Post', new_post_path %>

      </div>
      <div id="sidebar" class="col-1-3">
        <section>
          <div class="heading"><h2>About us</h2></div>
          <div class="content">
            <img src="/assets/thumb2.jpg" />
            <p align="justify">AnabtaTec is an Brazilian-Argentinian based outsourcing and software firm offering extended IT solutions and helping our clients reduce Time To Market (TTM) and enhance Return On Investment (ROI). Spezialazing in Ruby on Rails, iOS, Android, PHP, HTML5 and CSS3 Development.</p>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Services</h2></div>
          <div class="content">
            <ul>
              <li><a href="#">PHP</a></li>
              <li><a href="#">Ruby on Rails</a></li>
              <li><a href="#">iOS</a></li>
                 <li><a href="#">Android</a></li>
                    <li><a href="#">Networking</a></li>
                       <li><a href="#">Advanced IT Linux Infra-Structure</a></li>
                          <li><a href="#">HTML5</a></li>
                             <li><a href="#">CSS3</a></li>
                                <li><a href="#">Jquery Mobile</a></li>
            </ul>
          </div>
        </section>
        <section>
          <div class="heading"><h2>Latest Tweets</h2></div>
          <div class="content">
            <a class="twitter-timeline"  href="https://twitter.com/AnabtaTec"  data-widget-id="245951997168197632">Tweets by @AnabtaTec</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

          </div>
        </section>
      </div>
    </div>
  </div>
</section>

  

app/views/posts/new.html.erb
 <section id="content">
  <div class="zerogrid block">  
    <div class="row block04">
      <div class="col16">
        <section>
          <p>Home >> Posts >> Write a New Post</p>
        </section>
      </div>
    </div>
    
    <div class="row block05">
      <div id="main-content" class="col-2-3">

        
    <%= render 'form' %>

<%= link_to 'Back', posts_path %>

      </div>
    
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

   <section id="content">
  <div class="zerogrid block">  
    <div class="row block04">
      <div class="col16">
        <section>
          <p>Home >> post >> View Post</p>
        </section>
      </div>
    </div>
    
    <div class="row block05">
      <div id="main-content" class="col-2-3">

        <article>
          <div class="heading">
            <h2><a href=""><%= @post.title %></a></h2>
            <div class="info">Posted by <%= @post.fullname %> </div>
          </div>
          <div class="content">
            
            <p><%= @post.body %></p>
          </div>
        </article>
         
        <%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

      </div>
    
    </div>
  </div>
</section>